### ISSUE TITLE
Clearer "how to try this out" instructions / ways to have manual auth

### ISSUE THREAD

**Issue by bmann** [KinToday/kin-api-server#16]
I'm leaving this here but it actually pertains to the server_install file https://github.com/KinToday/kin-web-client/blob/master/docs/server_install.md

I was trying to give this a quick try by installing on Heroku, but it's clear that it really wants full hostnames, SSL, and all of the client secrets for the various providers.

A link to "Using pm2 with paas" would also be helpful -- http://pm2.keymetrics.io/docs/usage/use-pm2-with-cloud-providers/

I couldn't find where to only enable certain providers, so perhaps I could just try it with Github and something else easy.

I understand this was built to run big and in production -- and I really appreciate the open sourcing. Just giving some feedback on how to potentially let people try it quickly with a PaaS, and happy to tinker with this if someone can give me feedback on a minimal config that could work.

**Comment by zowesiouff** [comment]
> I was trying to give this a quick try by installing on Heroku, but it's clear that it really wants full hostnames, SSL, and all of the client secrets for the various providers.
Sadly yes, most of those are configurable though and wouldn't be too big a pain to adapt, I will try to do some tests on various PaaS offerings to ease the pain of standing it up there.

> A link to "Using pm2 with paas" would also be helpful -- http://pm2.keymetrics.io/docs/usage/use-pm2-with-cloud-providers/
done in [41975b7](https://github.com/KinToday/kin-web-client/commit/41975b754913da515051545f27579d2018a93bb7)

> I couldn't find where to only enable certain providers, so perhaps I could just try it with Github and something else easy.
In theory, provider are disabled by default until you give them a "value" for their various secrets. You will be greeted by a message like this in the logs when starting the server:
~~~~
WARN could not load file auth.js for source github: TypeError: OAuth2Strategy requires a clientID option
~~~~
(in this case we have no client ID / client secret for Github)

... except for Facebook and Google. They are used as an authentication mechanism to connect to Kin, and we haven't had time to make them by-passable if not configured.

**Comment by bmann** [comment]
OK, I will try and configure both Facebook and Google. Personally, I'd be fine with just one or the other, but I could also see the self hosting crowd not wanting either, but that would be up to them to figure out an auth scheme.

Other than PM2 + adding a main.js with Heroku, everything else seems OK, so it will mainly be about setting up all the config with a "temporary" URL like my-kin-api-server.herokuapp.com (which I think you can do https for pretty easily, too). I think you can let people who use the various PaaS services do the testing, it's up to us if that's what we want to use :)

Thanks for the quick response!

**Comment by zowesiouff** [comment]
Hey @bmann , did you run into any other issues while standing Kin up?

**Comment by bmann** [comment]
Haven't had a chance to sit down and complete this yet.

**Comment by hahn-kev** [comment]
Would it be possible to point the Kin Web Client at the public kin api server? That seems like it would drastically simplify development if you just want to work on the front end.

**Comment by zowesiouff** [comment]
@hahn-kev It's definitely doable, just need to update [config.js ](https://github.com/KinToday/kin-api-server/blob/master/src/api_server/sources/google/base.js) to the "live" endpoint:

```
export const API_HOSTNAME = {
    dev: "dev.kin.today:9000",
    prod: "api.kin.today",
    test: "placeholder"
}[KIN_ENV_NAME];
```

I'll close this for now, feel free to reopen.
