### ISSUE TITLE
Help getting the API server to run

### ISSUE THREAD

**Issue by niko001** [KinToday/kin-api-server#26]
Hi,

I've managed to get the web client to run without problems, but I get an `ERR_CONNECTION_REFUSED`-error in my browser when trying to load the Google connector. From my understanding, I should be able to load `https://mydomain.com:8080/1.0/authentication/google` after starting the API server?

On a fresh Ubuntu 14.04.5 system, I've installed redis, git, and node.js (v0.10.25)/node (v6.10.3), obtained a LetsEncrypt cert for my domain, and configured `config.js` and `secrets.js` (including adding client secrets for the Google and Facebook providers). I then ran
```
$ npm install
$ npm run build:dev
$ npm run start
```
and the server started without errors. I've also tried setting the `API_PORT` to 443 and 80, which doesn't make a difference.

Any help would be greatly appreciated! Thanks!

Nick

**Comment by zowesiouff** [comment]
1- Make sure the server's processes are running fine:`pm2 logs kin-api`
2- Is your API port set to `8080` or is it the port used by whatever you're using to serve the client files?

**Comment by niko001** [comment]
Thank you so much, Zowe, looking at the `pm2` logs did the trick! I thought that "running/online" in the `pm2` status table meant "running fine without errors". The issue was that the non-root pm2-service couldn't access the LetsEncrypt certificate folder. I corrected the permissions on `/etc/letsencrypt` and now it works perfectly! Thanks again!
