### ISSUE TITLE
Todoist dates are +1 for any timezone less than UTC

### ISSUE THREAD

**Issue by arbourd** [KinToday/kin-api-server#29]
Related to KinToday/kin-web-client#27

The Todoist sync API returns due dates as `23:59:00`, but converted to UTC from the users time zone. If the Todoist account is EDT (-4), the date will be reflected as `3:39:00 UTC`. Seemingly, Kin's server isn't taking the users Todoist timezone into account. 

The timezone should be available from the Todoist sync request:
```
"tz_info": {
            "hours": -4,
            "timezone": "America/Toronto",
            "is_dst": 1,
            "minutes": 0,
            "gmt_string": "-04:00"
        },
```

Could pass this value into the `moment.tz` to get the right date.

**Comment by zowesiouff** [comment]
Closing this for now, as #30 has been merged :) Feel free to reopen if we missed something.
